"use client"

import './globals.css'
import type { Metadata } from 'next'
import Provider from '@/components/Provider'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import { usePathname } from 'next/navigation'
import { checkIsPublicRoute } from '@/utils/functions/check-route'
import PrivateRoute from '@/components/config/PrivateRoute'

const metadata: Metadata = {
  title: 'Cloud Project',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const path = usePathname()

  const isPublic = checkIsPublicRoute(path)

  return (
    <html lang="pt-br">
      <body className='bg-white'>
        <Provider>
          <Navbar />
          {isPublic && children}

          {!isPublic && (
            <PrivateRoute>
              <div className="main">
                <div className='gradient' />
              </div>
              <main className='main-container min-h-[72vh] flex justify-center'>
                {children}
              </main>
            </PrivateRoute>
          )}
          <Footer />
        </Provider>
      </body>
    </html>
  )
}
